name: deploy-ftp--onPublished

on:
  release:
    types:
      - published

jobs:
  deploy-ftp--onPublished:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - uses: bamdadsabbagh/action-deploy-ftp@master
        with:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
          PATH_LOCAL: 'src'