name: docker-build-push-hub (published)

on:
  release:
    types:
      - published

jobs:
  docker-build-push-hub:
    runs-on: ubuntu-latest 
    steps:

      - uses: actions/checkout@master

      - uses: docker/build-push-action@master
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: ${{ secrets.DOCKER_REPO }}
          tag_with_ref: true
          tags: latest
